version: '3.8'

services:
  dev-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlserver
      MYSQL_DATABASE: bookstore
    ports:
      - '3333:3306'
  test-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlserver
      MYSQL_DATABASE: bookstore
    ports:
      - '4444:3306'
