version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysqlserver
      MYSQL_DATABASE: bookstore
    ports:
      - '3333:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
